/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                 */
/* file: aVersion.h						   */
/*                                                                 */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                 */
/* description: Cross-Platform implementation of stream I/O        */
/*              routines.  This file is generated by the automated */
/*              build process from aVersionTPL.h.                  */
/*                                                                 */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                 */
/* Copyright 1994-2008. Acroname Inc.                              */
/*                                                                 */
/* This software is the property of Acroname Inc.  Any             */
/* distribution, sale, transmission, or re-use of this code is     */
/* strictly forbidden except with permission from Acroname Inc.    */
/*                                                                 */
/* To the full extent allowed by law, Acroname Inc. also excludes  */
/* for itself and its suppliers any liability, wheither based in   */
/* contract or tort (including negligence), for direct,            */
/* incidental, consequential, indirect, special, or punitive       */
/* damages of any kind, or for loss of revenue or profits, loss of */
/* business, loss of information or data, or other financial loss  */
/* arising out of or in connection with this software, even if     */
/* Acroname Inc. has been advised of the possibility of such       */
/* damages.                                                        */
/*                                                                 */
/* Acroname Inc.                                                   */
/* www.acroname.com                                                */
/* 720-564-0373                                                    */
/*                                                                 */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef _aVersion_H_
#define _aVersion_H_

#define aVERSION_MAJOR		1L
#define aVERSION_MINOR		0L

#define aIO_BUILD_NUM		81111L
#define aUI_BUILD_NUM		81111L
#define aSTEM_BUILD_NUM		81111L
#define aTEAVM_BUILD_NUM	81111L
#define aSTEEP_BUILD_NUM	81111L
#define aSTEEPOPT_BUILD_NUM	81111L
#define aLEAF_BUILD_NUM		81111L
#define aPPRK_BUILD_NUM		81111L
#define aUI_BUILD_NUM		81111L
#define aGARCIA_BUILD_NUM	81111L
#define aLASER_BUILD_NUM	81111L

#define aCONSOLE_BUILD_NUM	81111L
#define aGP_BUILD_NUM		81111L
#define aCONFIG_BUILD_NUM	81111L
#define aSYMONYM_BUILD_NUM	81111L
#define aPACKAGE_BUILD_NUM	81111L
#define aROBOT_BUILD_NUM	81111L

#define aPACKAGE_MAJOR		1L
#define aPACKAGE_MINOR		0L
#define aSYMONYM_PKG_MAJOR	1L
#define aSYMONYM_PKG_MINOR	0L
#define aSYMONYM_PKG_BUILD	81111L

#define aNXPGM_BUILD            81111L

#define aCOPYRIGHT_LINE		"Copyright 1994-2008, Acroname Inc."

#endif /* _aVersion_H_ */
