# makefile: host/aStem/makefile.Linux

SHELL = /bin/sh
CC = gcc

ROOT := ../
LIBNAME := aStem

INCLUDES := -IaCommon \
	    -IaUnix \
	    -I../aCommon \
	    -I../aDebug/aUnix \
	    -I../aIO/aCommon \
	    -I../aIO/aUnix \
	    -I../aDebug/aSystem

VPATH := aCommon:aUnix:../aCommon

SOURCES := aAssert.c \
	   aMemLeakDebug.c \
	   aPacket.c \
	   aSerialRelayStream.c \
	   aStem.c \
	   aStemTEAFile.c

include $(ROOT)make_library.Linux
