# host/aRelease/aUnix/i686/makefile

SHELL = /bin/sh

.PHONY : all
all :

.PHONY: clean
clean :
	rm -f .DS_Store
	rm -rf .AppleFileInfo
	touch fooLog
	rm -f *Log
	rm -f StemDebug
	rm -f aIOTests
	rm -f debug.txt
	touch foo.config
	rm -f *.config
	touch foo.dat
	rm -f *.dat
	touch foo~
	rm -f *~

# don't do anything for now
.PHONY: output
output :
