# makefile: host/aTEAvm/makefile.Linux

SHELL = /bin/sh
CC = gcc

ROOT := ../
LIBNAME := aTEAvm

INCLUDES := -IaCommon \
	    -IaUnix \
	    -I../aCommon \
	    -I../aDebug/aUnix \
	    -I../aIO/aCommon \
	    -I../aIO/aUnix \
	    -I../aStem/aCommon \
	    -I../aStem/aUnix \
	    -I../aDebug/aSystem

VPATH := aCommon:aUnix:../aCommon

SOURCES := aAssert.c \
	   aMemLeakDebug.c \
	   aUtil.c \
	   aTEA.c \
	   aTEAvmInternal.c \
	   aTEAvm.c \
	   aStemCore.c

include $(ROOT)make_library.Linux
