#!/bin/bash
trap exit INT TERM EXIT
set -o nounset
set -o errexit

DESTS=$(cat ~/.scarabrc)

# All files in SCFILES variable should have absolute paths
for DEST in $DESTS; do
    echo Pushing $SCFILES to $DEST
    rsync -avzl --copy-links --relative -KO  --exclude="*.bag" --inplace $SCFILES $USER@$DEST:/

    echo "done!"
done
