#!/bin/bash
trap exit INT TERM EXIT
set -o nounset
set -o errexit

DESTS=$(cat ~/.scarabrc)

# All files in FILES variable should have absolute paths
FILES="$ROS_WORKSPACE $HOME/.bashrc $HOME/.gitconfig"
for DEST in $DESTS; do
    echo Deleting workspace $DEST
    ssh $USER@$DEST "rm -rf $ROS_WORKSPACE"
    echo "done!"
done
