# host/aRelease/aUnix/i586/makefile

SHELL = /bin/sh

.PHONY : all
all :

PLATFORM := $(shell uname)


.PHONY : clean
clean :
	rm -f .DS_Store
	rm -rf .AppleFileInfo
	touch fooLog
	rm -f *Log
	rm -f StemDebug
	touch foo.config
	rm -f *.config
	touch foo.dat
	rm -f *.dat
	touch foo~
	rm -f *~

# don't do anything for now
.PHONY: output
output :

