#! /usr/bin/env python

import roslib; roslib.load_manifest('human_friendly_navigation')
import rospy
import actionlib

from human_friendly_navigation.msg import *

if __name__ == '__main__':
    rospy.init_node('hfn_stop')
    action = sys.argv[1]
    rospy.loginfo("Asking %s to stop", action)
    client = actionlib.SimpleActionClient(action, MoveAction)
    present = client.wait_for_server(rospy.Duration(0.5))
    if present:
        goal = MoveGoal()
        goal.stop = True
        client.cancel_all_goals()
        result = client.send_goal_and_wait(goal, rospy.Duration(2.0))
        rospy.loginfo("Result: %s", result)
    else:
        rospy.loginfo("No server found")
