# host/aDebug/aUnix/i586/makefile

SHELL = /bin/sh

.PHONY : all
all :


aIO : libaIO.so.0.0
	ln -sf libaIO.so.0.0 libaIO.so.0
	ln -sf libaIO.so.0.0 libaIO.so

aUI : libaUI.so.0.0
	ln -sf libaUI.so.0.0 libaUI.so.0
	ln -sf libaUI.so.0.0 libaUI.so

aStem : libaStem.so.0.0
	ln -sf libaStem.so.0.0 libaStem.so.0
	ln -sf libaStem.so.0.0 libaStem.so

aTEAvm : libaTEAvm.so.0.0
	ln -sf libaTEAvm.so.0.0 libaTEAvm.so.0
	ln -sf libaTEAvm.so.0.0 libaTEAvm.so

aLeaf : libaLeaf.so.0.0
	ln -sf libaLeaf.so.0.0 libaLeaf.so.0
	ln -sf libaLeaf.so.0.0 libaLeaf.so

aSteepOpt : libaSteepOpt.so.0.0
	ln -sf libaSteepOpt.so.0.0 libaSteepOpt.so.0
	ln -sf libaSteepOpt.so.0.0 libaSteepOpt.so

aSteepGen : libaSteepGen.so.0.0
	ln -sf libaSteepGen.so.0.0 libaSteepGen.so.0
	ln -sf libaSteepGen.so.0.0 libaSteepGen.so

aSteep : libaSteep.so.0.0
	ln -sf libaSteep.so.0.0 libaSteep.so.0
	ln -sf libaSteep.so.0.0 libaSteep.so

aPPRK : libaPPRK.so.0.0
	ln -sf libaPPRK.so.0.0 libaPPRK.so.0
	ln -sf libaPPRK.so.0.0 libaPPRK.so

aGarcia : libaGarcia.so.0.0
	ln -sf libaGarcia.so.0.0 libaGarcia.so.0
	ln -sf libaGarcia.so.0.0 libaGarcia.so

aRobot : libaRobot.so.0.0
	ln -sf libaRobot.so.0.0 libaRobot.so.0
	ln -sf libaRobot.so.0.0 libaRobot.so

.PHONY: clean
clean :
	rm -f .DS_Store
	rm -rf .AppleFileInfo
	touch fooLog
	rm -f *Log
	rm -f StemDebug
	rm -f aIOTests
	rm -f debug.txt
	touch foo.config
	rm -f *.config
	touch foo.dat
	rm -f *.dat
	touch foo~
	rm -f *~

# don't do anything for now
.PHONY: output
output :
